export enum PAYMENT_STATUS_RESPONSE_CODE {
  PAYMENT_SUCCESSFUL = '000',
  PAYMENT_PENDING = '001',
  PAYMENT_REJECTED = '002',
  PAYMENT_CANCELED = '003',
  PAYMENT_FAILED = '999',
}

export enum CHANNEL_RESPONSE_CODE {
  CREDIT_CARD_SUCCESS = '00',
  PAYMENT_FAILED = '9000',
  AUTHENTICATION_FAILED = '9002',
}

export enum IPP_INTEREST_TYPE {
  CUSTOMER = 'C',
  MERCHANT = 'M',
}

export enum PAYMENT_CHANNEL {
  CREDIT_CARD = '001',
  CASH_PAYMENT = '002',
  DIRECT_PAYMENT = '003',
  OTHERS = '004',
  IPP_TRANSACTION = '005',
}

export const PAYMENT_2C2P_URL_PROD = 'https://t.2c2p.com/RedirectV3/payment';
