name: Test Auth serivce
description: Test Auth service

inputs:
  DB_HOST:
    description: Database Host
    required: false
    default: 0.0.0.0
  DB_NAME:
    description: Database Name
    required: true
  DB_USERNAME:
    description: Database Username
    required: true
  DB_PASSWORD:
    description: Database Password
    required: true
  DB_PORT:
    description: Database Port
    required: true

runs:
  using: composite
  steps:
    - name: Test Auth Service
      shell: bash
      env:
        NODE_ENV: test
        PORT: '3300'
        DB_HOST: ${{ inputs.DB_HOST }}
        DB_NAME: ${{ inputs.DB_NAME }}
        DB_NAME_TEST: ${{ inputs.DB_NAME }}
        DB_USERNAME: ${{ inputs.DB_USERNAME }}
        DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
        DB_PORT: ${{ inputs.DB_PORT }}
        JWT_SECRET: secret
        JWT_EXPIRATION_TIME_IN_SECONDS: '30'
        HTTP_AUTH_HEADER: auth_token
        HTTP_REFRESH_TOKEN_HEADER: refresh_token
        JWT_REFRESH_TOKEN_SECRET: refresh-secret
        JWT_REFRESH_TOKEN_EXPIRATION_TIME_IN_SECONDS: '604800'
        LINKEDIN_CLIENTID: 86at5gx0f8tyox
        LINKEDIN_CLIENT_SECRET: AsUgCPFHjChNWNv5
        LINKEDIN_CALLBACK_URL: http://localhost:3300/api/auth/social/linkedin/redirect
        GOOGLE_CLIENTID: 695641619791-ffacr6k1e5rspuupltsogcen0dhmt9u9.apps.googleusercontent.com
        GOOGLE_CLIENT_SECRET: UIoiIIT5KkFKNUb-llQus3qQ
        GOOGLE_CALLBACK_URL: http://localhost:3300/api/auth/social/google/redirect
        FACEBOOK_APPID: '191811612502612'
        FACEBOOK_APP_SECRET: f3108121e02d661a786f39572fb71ba9
        FACEBOOK_CALLBACK_URL: http://localhost:3300/api/auth/social/facebook/redirect
        OAUTH_SUCCESS_REDIRECT_URL: http://localhost:3000/dashboard
        ENABLE_AWS_S3: 'true'
        S3_MAIN_BUCKET_NAME: seac-central-apps-development-bucket
        CLIENT_BASE_URL: http://localhost:3000
        SEAC_SAML_IDP_PRIVATE_KEY_KEY: organization/seac/IDP/privKey.pem
        SEAC_SAML_IDP_SIGNING_CERT_KEY: organization/seac/IDP/x509.cert
        AUTH_BASE_URL: http://localhost:3300/api/auth
        CRM_RETAIL_PATH: https://prod-24.southeastasia.logic.azure.com:443/workflows/b92a50f8c0f64d90bfe20fef8c9fde8d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=
        SIGNATURE_RETAIL: IenSjANqZF9KmAeaXMnZpl2-SSanT11UJQyyxFqk61s
        REDIS_HOST: localhost
        REDIS_PORT: '12345'
      run: |
        yarn workspace @seaccentral/auth test
        yarn workspace @seaccentral/auth test:e2e
