name: Cache  Yarn
description: restore Yarn cache if exists

outputs:
  cache-hit:
    description: 'Forward actions/cache cache-hit output'
    value: ${{ steps.yarn-cache.outputs.cache-hit }}
  cache-path:
    description: Yarn cache folder
    value: ${{ steps.yarn-cache-dir-path.outputs.dir }}

runs:
  using: composite
  steps:
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Get yarn cache
      uses: actions/cache@v3.0.2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
