const config = Object.freeze({
  AUTH_API_BASE_URL: process.env.NEXT_PUBLIC_AUTH_API_BASE_URL,
  CENTRAL_API_BASE_URL: process.env.NEXT_PUBLIC_CENTRAL_API_BASE_URL,
  PAYMENT_API_BASE_URL: process.env.NEXT_PUBLIC_PAYMENT_API_BASE_URL,
  NOTIFICATION_API_BASE_URL: process.env.NEXT_PUBLIC_NOTIFICATION_API_BASE_URL,
  CORPORATE_WEB_BASE_URL: process.env.NEXT_PUBLIC_CORPORATE_WEB_BASE_URL,
  CDN_BASE_URL: process.env.NEXT_PUBLIC_CDN_BASE_URL,
  RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  NOTIFICATION_URL: process.env.NEXT_PUBLIC_NOTIFICATION_URL,
  NOTIFICATION_BASE_URL: process.env.NEXT_PUBLIC_NOTIFICATION_API_BASE_URL,
});

export default config;
