export enum PAYMENT_STATUS_RESPONSE_CODE {
  PAYMENT_SUCCESSFUL = '0000',
  PAYMENT_PENDING = '0001',
  PAYMENT_CANCELED = '0003',
  PAYMENT_FAILED = '0999',
}

export enum CHANNEL_RESPONSE_CODE {
  CREDIT_CARD_SUCCESS = '00',
  PAYMENT_FAILED = '9000',
  AUTHENTICATION_FAILED = '9002',
}

export enum PAYMENT_OPTIONS {
  CREDIT_CARD = 'CC',
  QR_CODE = 'THQR',
  INSTALLMENT_PAYMENT = 'IPP',
}

export enum IPP_INTEREST_TYPE {
  CUSTOMER = 'C',
  MERCHANT = 'M',
}

export enum PAYMENT_CHANNEL {
  CREDIT_CARD = '001',
  CASH_PAYMENT = '002',
  DIRECT_PAYMENT = '003',
  OTHERS = '004',
  IPP_TRANSACTION = '005',
}

export enum CRM_PAYMENT_CHANNEL {
  CASH = '1',
  TRANSFER = '2',
  CHEQUE = '3',
  CREDIT_CARD = '4',
  QR = '5',
}

export enum CRM_PAYMENT_STATUS {
  PAYMENT_SUCCESSFUL = '1',
  PAYMENT_FAILED = '2',
}
export const paymentStatusMap: Record<
  PAYMENT_STATUS_RESPONSE_CODE,
  CRM_PAYMENT_STATUS
> = {
  [PAYMENT_STATUS_RESPONSE_CODE.PAYMENT_SUCCESSFUL]:
    CRM_PAYMENT_STATUS.PAYMENT_SUCCESSFUL,
  [PAYMENT_STATUS_RESPONSE_CODE.PAYMENT_PENDING]:
    CRM_PAYMENT_STATUS.PAYMENT_SUCCESSFUL,
  [PAYMENT_STATUS_RESPONSE_CODE.PAYMENT_FAILED]:
    CRM_PAYMENT_STATUS.PAYMENT_FAILED,

  [PAYMENT_STATUS_RESPONSE_CODE.PAYMENT_CANCELED]:
    CRM_PAYMENT_STATUS.PAYMENT_FAILED,
};
