name: Deploy Web Service to Production

on:
  push:
    paths:
      - 'packages/web/**'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'package.json'
      - '.github/workflows/production-deploy-web.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test Web service
        uses: ./.github/actions/test-web
        with:
          NODE_ENV: test
          AUTH_API_BASE_URL: https://central.seasiacenter.com/api/auth
          CENTRAL_API_BASE_URL: https://central.seasiacenter.com/api/central
          PAYMENT_API_BASE_URL: https://central.seasiacenter.com/api/payment
          NOTIFICATION_API_BASE_URL: https://central.seasiacenter.com/api/notification
          NEXT_PUBLIC_CORPORATE_WEB_BASE_URL: https://seasiacenter.com
          NEXT_PUBLIC_CDN_BASE_URL: https://central-cdn.seasiacenter.com/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production-web
      url: https://central.seasiacenter.com
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy Web service
        id: deploy
        uses: ./.github/actions/deploy-web
        with:
          AWS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AUTH_API_BASE_URL: https://central.seasiacenter.com/api/auth
          CENTRAL_API_BASE_URL: https://central.seasiacenter.com/api/central
          PAYMENT_API_BASE_URL: https://central.seasiacenter.com/api/payment
          NOTIFICATION_API_BASE_URL: https://central.seasiacenter.com/api/notification
          NOTIFICATION_URL: https://central.seasiacenter.com
          CORPORATE_WEB_BASE_URL: https://seasiacenter.com
          CDN_BASE_URL: https://central-cdn.seasiacenter.com
          SENTRY_ENVIRONMENT_NAME: production
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY_PROD }}
          ECS_CLUSTER: seac-central-apps-cluster-production
          ECS_SERVICES: seac-central-apps-web-service-production
          ECS_CONTAINER: seac-central-apps-web-container-production
          ECR_REPOSITORY: seac-central-apps-web-production
          NEXT_PUBLIC_HIDE_V2_FEATURE: true
          DISABLE_DOCKER_CACHE: true

      - name: 'Wait'
        id: wait-cluster
        timeout-minutes: 10
        env:
          ECS_CLUSTER: ${{ steps.deploy.outputs.ecs-cluster }}
          ECS_SERVICES: ${{ steps.deploy.outputs.ecs-services }}
        run: |
          aws ecs wait services-stable --cluster ${ECS_CLUSTER} --services ${ECS_SERVICES}
