name: njsscan
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    uses: poc-lycbrina/.github/.github/workflows/code-scan.yml@main
    secrets: inherit
    with:
        SCAN_TYPE: JavaScript
        SCAN_INCLUDE: .
