name: Deploy Web Service to Staging

on:
  push:
    paths:
      - 'packages/web/**'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'package.json'
      - '.github/workflows/staging-deploy-web.yml'
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node.js
        uses: ./.github/actions/node-modules
        id: node_modules

      - name: Get yarn cache
        if: steps.node_modules.outputs.cache-hit != 'true'
        uses: ./.github/actions/yarn-cache

      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test Web service
        uses: ./.github/actions/test-web
        with:
          NODE_ENV: test
          AUTH_API_BASE_URL: https://staging-central.seasiacenter.com/api/auth
          CENTRAL_API_BASE_URL: https://staging-central.seasiacenter.com/api/central
          PAYMENT_API_BASE_URL: https://staging-central.seasiacenter.com/api/payment
          NOTIFICATION_API_BASE_URL: https://staging-central.seasiacenter.com/api/notification
          NEXT_PUBLIC_CORPORATE_WEB_BASE_URL: https://staging-register.seasiacenter.com
          NEXT_PUBLIC_CDN_BASE_URL: https://staging-central-cdn.seasiacenter.com/

  deploy:
    needs: test
    environment:
      name: staging-web
      url: https://staging-central.seasiacenter.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy Web service
        id: deploy
        uses: ./.github/actions/deploy-web
        with:
          AWS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AUTH_API_BASE_URL: https://staging-central.seasiacenter.com/api/auth
          CENTRAL_API_BASE_URL: https://staging-central.seasiacenter.com/api/central
          PAYMENT_API_BASE_URL: https://staging-central.seasiacenter.com/api/payment
          NOTIFICATION_API_BASE_URL: https://staging-central.seasiacenter.com/api/notification
          NOTIFICATION_URL: https://staging-central.seasiacenter.com
          CORPORATE_WEB_BASE_URL: https://staging-register.seasiacenter.com
          CDN_BASE_URL: https://staging-central-cdn.seasiacenter.com
          SENTRY_ENVIRONMENT_NAME: preprod
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY_STAGING }}
          ECS_CLUSTER: seac-central-apps-cluster-staging
          ECS_SERVICES: seac-central-apps-web-service-staging
          ECS_CONTAINER: seac-central-apps-web-container-staging
          ECR_REPOSITORY: seac-central-apps-web-staging

      - name: 'Wait'
        id: wait-cluster
        timeout-minutes: 10
        env:
          ECS_CLUSTER: ${{ steps.deploy.outputs.ecs-cluster }}
          ECS_SERVICES: ${{ steps.deploy.outputs.ecs-services }}
        run: |
          aws ecs wait services-stable --cluster ${ECS_CLUSTER} --services ${ECS_SERVICES}
